# Business use cases: shared by the header "Use cases" dropdown (partials.py) and the landing pages (solutions.py).
# `agents` names must match premade agents in tpl.py; availability tags come from tpl.AVAILABLE.

SOLUTIONS=[
 dict(slug='sales', nav='Sales & GTM', icon='<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',
  navdesc='Follow up every lead and book more demos.',
  title='AI Agents for Sales and GTM - Lead Follow-up and Booked Demos | AgentWorks',
  desc='AI agents for sales teams: research every new lead, follow up within minutes, watch competitors and report pipeline, working toward a booked-demos goal.',
  kicker='Use cases · Sales & GTM',
  h1='Every lead answered in minutes.', h1dim='More demos on the calendar.',
  lede='Leads go cold while founders and small sales teams juggle everything else. AgentWorks agents research each new lead, write a personal first email, follow up until they book or say no, and change the approach when replies drop.',
  goal=('Book more sales demos','Demos booked per week',('6','target 5')),
  pains=[('Leads wait hours for a reply','By the time someone answers, the lead has booked a call with a competitor.'),
         ('Follow-ups fall through','The third and fourth touch never happens, so most of the pipeline goes quiet.'),
         ('Nobody knows what works','Subject lines, timing and messages change by feel, not by results.')],
  agents=['Lead Follow-up','Competitor Watch','Weekly Business Report','Meeting Notes to Actions','Inbox Triage'],
  connectors='Gmail, Slack, your CRM through MCP, and any website through its own browser.',
  faq=[('Will it send emails without me?','Not unless you allow it. By default every outbound email waits for your approval, and you can raise the limit once you trust it. The Docs guide "Approvals and autonomy" explains the four levels.'),
       ('Does it work with our CRM?','Yes, through MCP or the CRM\'s website in the agent\'s own browser. HubSpot, Notion and Airtable are common starting points.'),
       ('How is this different from a sales sequencer?','A sequencer sends what you wrote on a schedule. AgentWorks owns the goal: it measures bookings, drops what doesn\'t work and tries what might.')]),
 dict(slug='shopify', nav='Shopify stores', icon='<path d="m21 8-9-5-9 5 9 5z"/><path d="M3 8v8l9 5 9-5V8M12 13v8"/>',
  navdesc='Stuck orders, reviews and support, handled.',
  title='AI Agents for Shopify Stores - Orders, Support and Reviews | AgentWorks',
  desc='AI agents for Shopify stores: catch stuck orders, answer customers on email and WhatsApp, reply to reviews and recover failed payments, working toward store goals.',
  kicker='Use cases · Shopify stores',
  h1='No order stuck, no customer left waiting.', h1dim='Even when you\'re not at the desk.',
  lede='Running a store means hundreds of small exceptions: a payment that failed, an order stuck in fulfilment, a customer asking where their parcel is. AgentWorks agents catch them, fix what they can, and tell you only about the ones that need you.',
  goal=('Keep every order moving','Orders stuck over 24 hours',('0','target 0')),
  pains=[('Orders get stuck quietly','Payment, fulfilment or shipping issues sit unnoticed until the customer complains.'),
         ('"Where is my order?" all day','The same questions arrive on email and WhatsApp, and each one takes you out of real work.'),
         ('Reviews go unanswered','Unhappy reviews stay public without a reply, and nobody links them back to the order.')],
  agents=['Order Watchdog','Support First Response','Review Responder','Failed Payment Recovery','Weekly Business Report'],
  connectors='Shopify, Gmail, WhatsApp and Slack, plus any supplier portal through its own browser.',
  faq=[('Can it change orders in Shopify?','Only what you grant. Reading orders is the default; updates, refunds and customer messages can each require your approval. The Docs guide "Set your first goal" shows how to frame these limits as rules.'),
       ('Does it work with my apps?','If an app has an API, an MCP server or a web page, an agent can use it.'),
       ('What about refunds?','Refunds above the limit you set always wait for you, with the order and the conversation attached.')]),
 dict(slug='support', nav='Customer support', icon='<path d="M3 18v-6a9 9 0 0 1 18 0v6"/><path d="M21 19a2 2 0 0 1-2 2h-1v-6h3zM3 19a2 2 0 0 0 2 2h1v-6H3z"/>',
  navdesc='Fast first replies, sensitive ones handed to you.',
  title='AI Agents for Customer Support - Fast First Response | AgentWorks',
  desc='AI support agents that answer customers on email and WhatsApp from your docs and order history, hand off sensitive cases, and work toward a first-response goal.',
  kicker='Use cases · Customer support',
  h1='First reply in minutes, not hours.', h1dim='Sensitive cases still come to you.',
  lede='Most support questions have an answer in your docs or the order history. AgentWorks agents answer those quickly in your voice, and route refunds, complaints and anything unusual to you with the context already gathered.',
  goal=('Answer customers faster','Median first response',('11 min','target 15 min')),
  pains=[('Customers wait too long','A slow first reply turns a simple question into an angry follow-up.'),
         ('The same answers, again','Your team rewrites the same explanation fifty times a week.'),
         ('Hand-offs lose context','When a case needs a human, they start from scratch.')],
  agents=['Support First Response','Inbox Triage','Review Responder','Meeting Notes to Actions'],
  connectors='Gmail, WhatsApp and Slack, your help docs, and your order or billing system through MCP.',
  faq=[('Will customers know it\'s an agent?','That\'s your call. Replies use your tone and signature, and you decide what it may send without review.'),
       ('What does it hand off?','Anything over your limits: refunds, legal or angry messages, and topics you mark as sensitive. See "Approvals and autonomy" in Docs for how limits work.'),
       ('Does it learn our answers?','Yes. Approved answers become part of its knowledge base, so the next reply is better.')]),
 dict(slug='finance', nav='Finance & billing', icon='<path d="M4 4h12l4 4v12H4z"/><path d="M9 12h6M9 16h4M9 8h3"/>',
  navdesc='Chase invoices, recover payments, weekly numbers.',
  title='AI Agents for Finance - Invoice Chasing and Payment Recovery | AgentWorks',
  desc='AI agents for small-business finance: chase overdue invoices politely, recover failed payments and deliver a weekly business report, working toward a cash goal.',
  kicker='Use cases · Finance & billing',
  h1='Get paid on time,', h1dim='without being the one who chases.',
  lede='Chasing invoices is awkward and easy to postpone. AgentWorks agents watch receivables, send polite escalating reminders from your own inbox, recover failed card payments and put the numbers in front of you every Monday.',
  goal=('Get paid faster','Overdue invoices',('8.9%','of receivables, target under 5%')),
  pains=[('Invoices go overdue','Nobody wants to send the awkward third reminder, so it doesn\'t get sent.'),
         ('Failed payments churn customers','A card expires and the customer is gone before anyone notices.'),
         ('Numbers arrive late','The weekly picture takes an afternoon of spreadsheets, so it rarely happens.')],
  agents=['Invoice Chaser','Failed Payment Recovery','Weekly Business Report'],
  connectors='Stripe and QuickBooks, Gmail for reminders, and Slack for the weekly report.',
  faq=[('Will it email my customers?','From your own mailbox, in your tone, and only after your approval until you tell it otherwise. Key accounts can get a softer template. The Docs guide "Approvals and autonomy" explains the four levels.'),
       ('Does it touch money?','No. It reads invoices and payment status and sends reminders; it never moves money.'),
       ('What does the weekly report include?','Revenue, overdue invoices, failed payments and anything unusual, with the numbers behind each line.')]),
 dict(slug='marketing', nav='Marketing & growth', icon='<path d="M3 17l6-6 4 4 8-8"/><path d="M15 7h6v6"/>',
  navdesc='SEO, AI search visibility and conversion.',
  title='AI Agents for Marketing and Growth - SEO and AI Search Visibility | AgentWorks',
  desc='AI growth agents that find winnable keywords, track whether ChatGPT and Perplexity cite you, watch competitors and explain conversion changes, working toward a growth goal.',
  kicker='Use cases · Marketing & growth',
  h1='Show up in Google and in ChatGPT.', h1dim='And know why the number moved.',
  lede='Search now happens in Google and in AI assistants. AgentWorks agents find the keywords you can win, check whether ChatGPT, Perplexity and Gemini recommend you or your competitors, and close the gaps week by week.',
  goal=('Grow organic traffic','Organic clicks per week',('+9%','this quarter, target +15%')),
  pains=[('AI search is a blind spot','You don\'t know whether AI assistants recommend you or your competitors.'),
         ('SEO work never gets prioritised','Technical fixes and content gaps sit in a doc nobody opens.'),
         ('Drops go unexplained','Traffic or conversion moves and nobody knows which page or source caused it.')],
  agents=['SEO Intelligence','AI Visibility','Competitor Watch','Weekly Business Report'],
  connectors='Search Console, analytics through MCP, your CMS, and its own browser for AI assistants and competitor sites.',
  faq=[('Which AI assistants does it check?','ChatGPT, Perplexity, Gemini and Google AI Overviews, using a fixed set of questions your buyers ask.'),
       ('Does it publish content?','It writes page-level briefs and drafts. Publishing waits for your approval. See "Approvals and autonomy" in Docs for how approvals work.'),
       ('Is this available today?','Yes. SEO Intelligence and AI Visibility are live playbooks today.')]),
]

def sol_nav_items():
    items=[(f'/solutions/{u["slug"]}/',u['nav'],u['navdesc'],u['icon']) for u in SOLUTIONS]
    items.append(('/enterprise/','Engineering teams','QA, incidents, security and cloud cost.','<path d="m8 9-4 3 4 3M16 9l4 3-4 3"/>'))
    return items
