# Enterprise use cases: shared by the header dropdown (partials.py) and the landing pages (usecases.py).
USECASES=[
 dict(slug='release-quality', nav='Release quality', icon='<path d="M5 12l4 4 10-10"/>',
  navdesc='AI QA that writes, runs and repairs your browser tests.',
  title='AgentWorks for Release Quality - AI QA and Self-Healing Tests',
  desc='AI agents that test critical user journeys, repair broken browser tests and gate every release with an auditable pass, fail or needs-review decision.',
  kicker='Enterprise · Release quality',
  h1='No release ships without a QA decision.', h1dim='AI agents own the tests.',
  lede='Your team ships faster with AI, so QA is now the bottleneck. AgentWorks agents run your critical journeys on every change, repair tests that broke for the wrong reasons, and publish a decision you can audit.',
  goal=('Every release has a recorded QA decision','Releases gated',('100%','of releases, target 100%')),
  pains=[('Tests break for the wrong reasons','Selectors change, flaky timing, test data drift. The team starts ignoring red builds.'),
         ('Critical journeys aren\'t covered','Signup, checkout, permissions: the flows that hurt most are tested least.'),
         ('Nobody can say why a release shipped','There is no record of which suites ran against which build.')],
  steps=[('Map the journeys','Agents set up the browser once, save verified locators, and turn your critical journeys into tests.'),
         ('Gate every change','Each PR or build is bound to the suites it needs, with video, console and network evidence kept per attempt.'),
         ('Repair, don\'t ignore','When a test fails, agents classify the cause. Test-only breakages get a reviewed repair; real bugs become findings.'),
         ('Decide and record','A pass, fail or needs-review decision is published with links to every run behind it.')],
  playbooks=['Basic Browser Setup','Critical Journey Validation','Release and PR Quality Gate','Browser Test Self-Healing','Flaky-Test Detection and Stabilization','Authentication and Session Validation','Scheduled Regression and Synthetic Monitoring','Browser Performance Validation'],
  faq=[('Does it replace our test framework?','No. Agents write and run Playwright tests in your repository and keep them as normal code your team can read and change.'),
       ('Can it change tests without review?','Only test-only repairs are proposed, and they wait for review by default. Production code is never touched by the QA agents.'),
       ('What if a failure is a real bug?','It becomes a finding with video, logs and steps to reproduce, and the release gate reports it as a fail.')]),
 dict(slug='incident-response', nav='Incident response', icon='<path d="M12 3 2 20h20z"/><path d="M12 10v4M12 17h.01"/>',
  navdesc='First RCA before the war room fills up.',
  title='AgentWorks for Incident Response - AI Triage, RCA and Remediation',
  desc='AI agents that triage CI and deploy failures, correlate incident signals, write an evidence-backed first RCA, prepare approved remediation and track follow-ups.',
  kicker='Enterprise · Incident response',
  h1='The first RCA is ready before the war room is.', h1dim='With evidence, not guesses.',
  lede='Alerts, logs and deploys live in different tools, and every incident starts from zero. AgentWorks agents correlate the signals, write a first root-cause analysis with evidence and unknowns, and prepare remediation that runs only after approval.',
  goal=('Time to first evidence-backed RCA','Minutes to first RCA',('18 min','median, target under 30')),
  pains=[('Every incident starts from zero','Someone has to pull logs, deploy history and dashboards before anyone can think.'),
         ('CI failures pile up','Red builds wait for a human to decide whether it is the code, the test or the infrastructure.'),
         ('Post-mortem actions disappear','Follow-ups get written, then nobody checks whether they were done.')],
  steps=[('Triage','CI and deployment failures are classified with evidence, and safe policy actions run automatically.'),
         ('Investigate','Signals are correlated into one incident record with impact, severity, timeline and a first RCA.'),
         ('Remediate','An exact remediation is prepared, validated and approved, then executed through authorized paths with rollback ready.'),
         ('Follow through','A sourced post-incident review creates tracked actions and checks they were actually completed.')],
  playbooks=['CI and Deployment Failure Triage','Incident Investigation and Coordination','Governed Remediation and Recovery','Post-Incident Review and Actions'],
  faq=[('Will it take actions in production on its own?','Not unless you allow it. Remediation is prepared and validated, then waits for approval; execution runs only through the paths you authorize.'),
       ('Which tools does it read?','Whatever your team uses for CI, logs, metrics and alerts, through MCP servers, APIs or its own browser.'),
       ('Does it replace our incident tool?','No. It works alongside it, posting status and findings where your team already coordinates.')]),
 dict(slug='security-testing', nav='Security testing', icon='<path d="M12 3 4 6v6c0 5 3.5 8 8 9 4.5-1 8-4 8-9V6z"/>',
  navdesc='Authorized AppSec and permission testing, driven to closure.',
  title='AgentWorks for Security Testing - AI AppSec and Permission Testing',
  desc='Authorized AI security testing across web, API, code, dependencies and secrets, plus role and tenant permission checks, with reviewed fixes and verified closure.',
  kicker='Enterprise · Security testing',
  h1='Security findings that end in a fix.', h1dim='Not in a longer backlog.',
  lede='Scanners are good at finding problems and bad at finishing them. AgentWorks agents run authorized assessments, test who can see and do what across roles and tenants, and drive reviewed fixes through to verified closure.',
  goal=('Critical findings closed within 14 days','Critical findings open',('2','open, target 0 older than 14 days')),
  pains=[('The backlog only grows','Hundreds of findings, no owner, no way to tell which ones matter.'),
         ('Access bugs slip through','Broken permissions between roles, owners and tenants rarely show up in scanners.'),
         ('Fixed is never verified','Tickets get closed without anyone re-testing the issue.')],
  steps=[('Authorize','Scope, targets and rules of engagement are written down and approved before any test runs.'),
         ('Assess','Web, API, code, dependency, secret and configuration checks run against the approved attack surface.'),
         ('Test permissions','A permission matrix across roles, ownership and tenants is turned into tests that run every release.'),
         ('Fix and verify','Findings are reviewed for severity, fixes go through approval, and each one is re-tested before it is closed.')],
  playbooks=['Application Security Assessment and Remediation','Role and Permission Validation','Authentication and Session Validation'],
  faq=[('Is this a penetration test?','It runs authorized, scoped assessments continuously. It complements, and does not replace, an independent pentest where you need one for compliance.'),
       ('Where does sensitive evidence go?','Evidence stays in your environment with restricted access. Nothing leaves unless you configure it to.'),
       ('Can it push fixes itself?','Fixes are proposed and reviewed first. Delivery follows your normal approval path.')]),
 dict(slug='cloud-cost', nav='Cloud cost', icon='<path d="M7 18a5 5 0 1 1 1-9.9A6 6 0 0 1 19 10a4 4 0 0 1-1 8z"/>',
  navdesc='Find cost anomalies and prove the savings.',
  title='AgentWorks for Cloud Cost - AI FinOps with Verified Savings',
  desc='AI agents that catch cloud cost anomalies, propose evidence-backed rightsizing, prepare reviewed IaC changes and verify the real savings and service health afterwards.',
  kicker='Enterprise · Cloud cost',
  h1='Cut cloud cost, then prove it.', h1dim='Without breaking what\'s running.',
  lede='Cost tools show you the spike. Someone still has to find the cause, change the infrastructure safely and check the savings were real. AgentWorks agents do that loop, with every change reviewed and every saving verified.',
  goal=('Verified monthly savings','Monthly savings verified',('$4,200','this month, tracked per change')),
  pains=[('Spikes get noticed late','The bill arrives before anyone asks why.'),
         ('Rightsizing feels risky','Nobody wants to be the one who shrank the database before a traffic peak.'),
         ('Savings are estimates','Recommendations promise savings; nobody checks what actually happened.')],
  steps=[('Baseline','Scope, budgets and change policy are set, and cost drivers are mapped per service.'),
         ('Detect','Anomalies are classified by cause, with the usage and utilization evidence behind them.'),
         ('Propose','Rightsizing candidates come with cost, capacity and risk evidence, as a validated IaC diff for review.'),
         ('Verify','After the change, realized savings and service health are measured, and the change is kept or rolled back.')],
  playbooks=['Cost Anomaly to Verified Savings','API Performance Validation','Browser Performance Validation'],
  faq=[('Which clouds does it support?','Whatever your team can reach through APIs, CLIs or MCP servers, including AWS, GCP and Azure.'),
       ('Does it change infrastructure directly?','It prepares a reviewable IaC diff. Changes go through your normal review and deploy path.'),
       ('How are savings measured?','Against a recorded baseline for the affected services, after the change has run long enough to compare.')]),
 dict(slug='growth-analytics', nav='Growth analytics', icon='<path d="M3 17l6-6 4 4 8-8"/><path d="M15 7h6v6"/>',
  navdesc='An AI growth analyst for funnels, retention and search.',
  title='AgentWorks for Growth Analytics - An AI Growth Analyst',
  desc='AI agents that explain conversion drops, find what predicts retention, track SEO and AI-search visibility, and follow experiments through to a KPI verdict.',
  kicker='Enterprise · Growth analytics',
  h1='Know why the number moved.', h1dim='And what to do about it this week.',
  lede='Dashboards show that conversion dropped. They don\'t say which segment, page or source caused it, or whether last month\'s fix worked. AgentWorks agents investigate, recommend and check the result.',
  goal=('Signup-to-paid conversion','Conversion rate',('4.1%','from 3.4%, target 4.5%')),
  pains=[('Drops get noticed, not explained','Someone spends two days slicing data every time a number moves.'),
         ('Experiments don\'t close','Changes ship, and nobody checks whether the KPI actually improved.'),
         ('AI search is a blind spot','You don\'t know whether ChatGPT or Perplexity recommend you or your competitors.')],
  steps=[('Connect the data','Traffic, product, billing and feedback data are joined with customer identity and quality checks.'),
         ('Investigate','Conversion changes are attributed to the segment, page, device or source, with session evidence.'),
         ('Recommend','Findings become prioritized experiments with pre-registered targets and tracked actions.'),
         ('Verify','After a change ships, the KPI is read out with a verdict: it worked, it didn\'t, or it needs more time.')],
  playbooks=['Growth Data Foundation','Funnel and Conversion Intelligence','Activation and Retention Intelligence','Growth Experimentation and Follow-Through','SEO Intelligence','AI Visibility Intelligence'],
  faq=[('Which analytics tools does it work with?','Product analytics, billing, CRM and search tools your team already uses, through APIs, MCP servers or its own browser.'),
       ('Does it make changes to the product?','No. It recommends and tracks actions in your tools; your team decides what ships.'),
       ('How is this different from a BI dashboard?','A dashboard shows the number. The agents own a goal: they investigate, propose, and check whether the change worked.')]),
]

def uc_nav_items():
    return [(f'/enterprise/{u["slug"]}/',u['nav'],u['navdesc'],u['icon']) for u in USECASES]

