# Enterprise use cases: shared by the header dropdown (partials.py) and the landing pages (usecases.py).
USECASES=[
 dict(slug='release-quality', nav='Release quality', icon='<path d="M5 12l4 4 10-10"/>',
  navdesc='AI QA that writes, runs and repairs your browser tests.',
  title='AgentWorks for Release Quality - AI QA and Self-Healing Tests',
  desc='AI agents that test critical user journeys, repair broken browser tests and gate every release with an auditable pass, fail or needs-review decision.',
  kicker='Enterprise · Release quality',
  h1='No release ships without a QA decision.', h1dim='AI agents own the tests.',
  lede='Your team ships faster with AI, so QA is now the bottleneck. AgentWorks agents run your critical journeys on every change, repair tests that broke for the wrong reasons, and publish a decision you can audit.',
  goal=('Every release has a recorded QA decision','Releases gated',('100%','of releases, target 100%')),
  pains=[('Tests break for the wrong reasons','Selectors change, flaky timing, test data drift. The team starts ignoring red builds.'),
         ('Critical journeys aren\'t covered','Signup, checkout, permissions: the flows that hurt most are tested least.'),
         ('Nobody can say why a release shipped','There is no record of which suites ran against which build.')],
  steps=[('Map the journeys','Agents set up the browser once, save verified locators, and turn your critical journeys into tests.'),
         ('Gate every change','Each PR or build is bound to the suites it needs, with video, console and network evidence kept per attempt.'),
         ('Repair, don\'t ignore','When a test fails, agents classify the cause. Test-only breakages get a reviewed repair; real bugs become findings.'),
         ('Decide and record','A pass, fail or needs-review decision is published with links to every run behind it.')],
  playbooks=['Basic Browser Setup','Critical Journey Validation','Release and PR Quality Gate','Browser Test Self-Healing','Flaky-Test Detection and Stabilization','Authentication and Session Validation','Scheduled Regression and Synthetic Monitoring','Browser Performance Validation'],
  faq=[('Does it replace our test framework?','No. Agents write and run Playwright tests in your repository and keep them as normal code your team can read and change.'),
       ('Can it change tests without review?','Only test-only repairs are proposed, and they wait for review by default. Production code is never touched by the QA agents.'),
       ('What if a failure is a real bug?','It becomes a finding with video, logs and steps to reproduce, and the release gate reports it as a fail.')]),
 dict(slug='incident-response', nav='Incident response', icon='<path d="M12 3 2 20h20z"/><path d="M12 10v4M12 17h.01"/>',
  navdesc='First RCA before the war room fills up.',
  title='AgentWorks for Incident Response - AI Triage, RCA and Remediation',
  desc='AI agents that triage CI and deploy failures, correlate incident signals, write an evidence-backed first RCA, prepare approved remediation and track follow-ups.',
  kicker='Enterprise · Incident response',
  h1='The first RCA is ready before the war room is.', h1dim='With evidence, not guesses.',
  lede='Alerts, logs and deploys live in different tools, and every incident starts from zero. AgentWorks agents correlate the signals, write a first root-cause analysis with evidence and unknowns, and prepare remediation that runs only after approval.',
  goal=('Time to first evidence-backed RCA','Minutes to first RCA',('18 min','median, target under 30')),
  pains=[('Every incident starts from zero','Someone has to pull logs, deploy history and dashboards before anyone can think.'),
         ('CI failures pile up','Red builds wait for a human to decide whether it is the code, the test or the infrastructure.'),
         ('Post-mortem actions disappear','Follow-ups get written, then nobody checks whether they were done.')],
  steps=[('Triage','CI and deployment failures are classified with evidence, and safe policy actions run automatically.'),
         ('Investigate','Signals are correlated into one incident record with impact, severity, timeline and a first RCA.'),
         ('Remediate','An exact remediation is prepared, validated and approved, then executed through authorized paths with rollback ready.'),
         ('Follow through','A sourced post-incident review creates tracked actions and checks they were actually completed.')],
  playbooks=['CI and Deployment Failure Triage','Incident Investigation and Coordination','Governed Remediation and Recovery','Post-Incident Review and Actions'],
  faq=[('Will it take actions in production on its own?','Not unless you allow it. Remediation is prepared and validated, then waits for approval; execution runs only through the paths you authorize.'),
       ('Which tools does it read?','Whatever your team uses for CI, logs, metrics and alerts, through MCP servers, APIs or its own browser.'),
       ('Does it replace our incident tool?','No. It works alongside it, posting status and findings where your team already coordinates.')]),
 dict(slug='security-testing', nav='Security testing', icon='<path d="M12 3 4 6v6c0 5 3.5 8 8 9 4.5-1 8-4 8-9V6z"/>',
  navdesc='Authorized AppSec and permission testing, driven to closure.',
  title='AgentWorks for Security Testing - AI AppSec and Permission Testing',
  desc='Authorized AI security testing across web, API, code, dependencies and secrets, plus role and tenant permission checks, with reviewed fixes and verified closure.',
  kicker='Enterprise · Security testing',
  h1='Security findings that end in a fix.', h1dim='Not in a longer backlog.',
  lede='Scanners are good at finding problems and bad at finishing them. AgentWorks agents run authorized assessments, test who can see and do what across roles and tenants, and drive reviewed fixes through to verified closure.',
  goal=('Critical findings closed within 14 days','Critical findings open',('2','open, target 0 older than 14 days')),
  pains=[('The backlog only grows','Hundreds of findings, no owner, no way to tell which ones matter.'),
         ('Access bugs slip through','Broken permissions between roles, owners and tenants rarely show up in scanners.'),
         ('Fixed is never verified','Tickets get closed without anyone re-testing the issue.')],
  steps=[('Authorize','Scope, targets and rules of engagement are written down and approved before any test runs.'),
         ('Assess','Web, API, code, dependency, secret and configuration checks run against the approved attack surface.'),
         ('Test permissions','A permission matrix across roles, ownership and tenants is turned into tests that run every release.'),
         ('Fix and verify','Findings are reviewed for severity, fixes go through approval, and each one is re-tested before it is closed.')],
  playbooks=['Application Security Assessment and Remediation','Role and Permission Validation','Authentication and Session Validation'],
  faq=[('Is this a penetration test?','It runs authorized, scoped assessments continuously. It complements, and does not replace, an independent pentest where you need one for compliance.'),
       ('Where does sensitive evidence go?','Evidence stays in your environment with restricted access. Nothing leaves unless you configure it to.'),
       ('Can it push fixes itself?','Fixes are proposed and reviewed first. Delivery follows your normal approval path.')]),
 dict(slug='cloud-cost', nav='Cloud cost', icon='<path d="M7 18a5 5 0 1 1 1-9.9A6 6 0 0 1 19 10a4 4 0 0 1-1 8z"/>',
  navdesc='Find cost anomalies and prove the savings.',
  title='AgentWorks for Cloud Cost - AI FinOps with Verified Savings',
  desc='AI agents that catch cloud cost anomalies, propose evidence-backed rightsizing, prepare reviewed IaC changes and verify the real savings and service health afterwards.',
  kicker='Enterprise · Cloud cost',
  h1='Cut cloud cost, then prove it.', h1dim='Without breaking what\'s running.',
  lede='Cost tools show you the spike. Someone still has to find the cause, change the infrastructure safely and check the savings were real. AgentWorks agents do that loop, with every change reviewed and every saving verified.',
  goal=('Verified monthly savings','Monthly savings verified',('$4,200','this month, tracked per change')),
  pains=[('Spikes get noticed late','The bill arrives before anyone asks why.'),
         ('Rightsizing feels risky','Nobody wants to be the one who shrank the database before a traffic peak.'),
         ('Savings are estimates','Recommendations promise savings; nobody checks what actually happened.')],
  steps=[('Baseline','Scope, budgets and change policy are set, and cost drivers are mapped per service.'),
         ('Detect','Anomalies are classified by cause, with the usage and utilization evidence behind them.'),
         ('Propose','Rightsizing candidates come with cost, capacity and risk evidence, as a validated IaC diff for review.'),
         ('Verify','After the change, realized savings and service health are measured, and the change is kept or rolled back.')],
  playbooks=['Cost Anomaly to Verified Savings','API Performance Validation','Browser Performance Validation'],
  faq=[('Which clouds does it support?','Whatever your team can reach through APIs, CLIs or MCP servers, including AWS, GCP and Azure.'),
       ('Does it change infrastructure directly?','It prepares a reviewable IaC diff. Changes go through your normal review and deploy path.'),
       ('How are savings measured?','Against a recorded baseline for the affected services, after the change has run long enough to compare.')]),
 dict(slug='growth-analytics', nav='Growth analytics', icon='<path d="M3 17l6-6 4 4 8-8"/><path d="M15 7h6v6"/>',
  navdesc='An AI growth analyst for funnels, retention and search.',
  title='AgentWorks for Growth Analytics - An AI Growth Analyst',
  desc='AI agents that explain conversion drops, find what predicts retention, track SEO and AI-search visibility, and follow experiments through to a KPI verdict.',
  kicker='Enterprise · Growth analytics',
  h1='Know why the number moved.', h1dim='And what to do about it this week.',
  lede='Dashboards show that conversion dropped. They don\'t say which segment, page or source caused it, or whether last month\'s fix worked. AgentWorks agents investigate, recommend and check the result.',
  goal=('Signup-to-paid conversion','Conversion rate',('4.1%','from 3.4%, target 4.5%')),
  pains=[('Drops get noticed, not explained','Someone spends two days slicing data every time a number moves.'),
         ('Experiments don\'t close','Changes ship, and nobody checks whether the KPI actually improved.'),
         ('AI search is a blind spot','You don\'t know whether ChatGPT or Perplexity recommend you or your competitors.')],
  steps=[('Connect the data','Traffic, product, billing and feedback data are joined with customer identity and quality checks.'),
         ('Investigate','Conversion changes are attributed to the segment, page, device or source, with session evidence.'),
         ('Recommend','Findings become prioritized experiments with pre-registered targets and tracked actions.'),
         ('Verify','After a change ships, the KPI is read out with a verdict: it worked, it didn\'t, or it needs more time.')],
  playbooks=['Growth Data Foundation','Funnel and Conversion Intelligence','Activation and Retention Intelligence','Growth Experimentation and Follow-Through','SEO Intelligence','AI Visibility Intelligence'],
  faq=[('Which analytics tools does it work with?','Product analytics, billing, CRM and search tools your team already uses, through APIs, MCP servers or its own browser.'),
       ('Does it make changes to the product?','No. It recommends and tracks actions in your tools; your team decides what ships.'),
       ('How is this different from a BI dashboard?','A dashboard shows the number. The agents own a goal: they investigate, propose, and check whether the change worked.')]),
 dict(slug='workbench', path='/code/', page=False, group='AI platform for teams', nav='Code', icon='<path d="m8 9-4 3 4 3M16 9l4 3-4 3"/>',
  navdesc='An AI workspace for every employee, with cost and usage visible to the company.',
  title='AgentWorks Workbench - Share Your Team\'s AI Plans and Measure Usage',
  desc='Move scattered personal Claude Code, Codex and Cursor subscriptions onto one AgentWorks server. People use shared Crew agents in chat or the live terminal, and you see usage and cost by person, Crew, workflow and model.',
  kicker='Workbench',
  h1='Every AI subscription in one place.', h1dim='Shared, governed and measured.',
  lede='Today everyone runs Claude Code, Codex or Cursor on their own laptop, on their own plan. You can\'t share them, see what they cost, or control what they touch. Workbench puts your team\'s AI plans on one AgentWorks server. People work with shared Crew agents in chat or in the live terminal, and you see usage by person, Crew and model.',
  goal=('Know what AI costs, by team','Agent work attributed to a person or Crew',('100%','of recorded runs, target 100%')),
  pains=[('Plans are scattered across laptops','Each engineer pays for, or expenses, their own Claude, ChatGPT or Cursor plan. Some seats sit idle while others hit their limits.'),
         ('No one knows what AI costs','There is no view of usage by person, team or project, so AI budgets are guesses.'),
         ('Agents run with full laptop access','A personal agent can see every file, token and repository on the machine, with no record of what it did.')],
  steps=[('Connect the plans once','An admin connects your Claude, ChatGPT, Cursor and other plans on the server as shared accounts. Anyone can still add a private account for their own work.'),
         ('Give each team its Crew','Set up shared Crew agents with the skills, memory and tools each team needs. People reach them in chat, Slack or WhatsApp.'),
         ('Chat or the live terminal','Work in plain chat, or switch to the vendor\'s own CLI running live in a terminal on the server. Every command it runs is sandboxed to the folders it is granted.'),
         ('Measure and govern','See recorded usage and cost by user, Crew, workflow and model. Roles, per-workflow access and a full run log keep it governed.')],
  how_h2='One server for every agent.', how_h2dim='Chat or terminal, your choice.',
  cta_h2='Bring your plans in.', cta_h2dim='See usage in week one.',
  cta_p='We move one team onto a shared server with you, connect its plans, and show usage and cost by person and Crew from the first week.',
  list_kicker='What you get', list_h2='One server.', list_h2dim='Every agent, every plan, every run.',
  list_lede='What IT and engineering leaders get from day one, instead of subscriptions scattered across laptops.',
  list_cta='See what you get',
  playbooks=['Shared server accounts for Claude Code, Codex, Cursor, Pi and Muse','Private accounts for people who bring their own plan','Crew agents in chat, Slack, WhatsApp or the live terminal','Usage and cost by user, Crew, workflow, project and model','Roles, per-workflow access and SSO','Sandboxed code execution per agent, a private /tmp and home folder for each workflow or Crew, a secrets vault and a full run log'],
  faq=[('Can we share one subscription across people?','That depends on the plan. Team, business and enterprise plans and API keys are made for shared use; personal plans usually are not, so check each vendor\'s terms. AgentWorks runs whichever accounts you connect.'),
       ('Can people still use their own plan?','Yes. Anyone can add a private account for their own work, next to the shared server account an admin manages.'),
       ('How is usage measured?','Every agent call is recorded with its user, Crew or workflow, provider and model, with token counts and cost. Subscription usage shows as a subscription-equivalent estimate, not as your bill.'),
       ('Can one person\'s agent reach another person\'s files?','Not through the commands it runs. Every shell command and script gets its own private /tmp and runs in a Linux sandbox limited to the folders its workflow or Crew was granted, and it can\'t reach other people\'s agent terminals. Each workflow or Crew also has its own home folder, so git logins, SSH keys and CLI settings stay with it.'),
       ('What does the terminal mode give power users?','The vendor\'s own CLI, such as Claude Code, Codex or Cursor, running live on the server, with every command it runs sandboxed. They get the full tool without it touching their laptop, and every run is logged.')]),
 dict(slug='expert-crews', path='/crews/', page=False, group='AI platform for teams', nav='Expert Crews', icon='<circle cx="12" cy="7" r="3"/><path d="M5 20a7 7 0 0 1 14 0"/><path d="M3 11h3M18 11h3"/>',
  navdesc='Build a DevOps or product expert once; every engineer asks it from their own CLI.',
  title='AgentWorks Expert Crews - Build Expert AI Agents Once, Share Them Across Your Company',
  desc='Teams build specialist Crew agents, such as a DevOps, RDS or product expert, and share them across the company. Engineers ask them from Claude Code, Codex, Cursor, ChatGPT or Claude through MCP or the CLI.',
  kicker='Expert Crews',
  h1='Your best experts, available to every engineer.', h1dim='As agents they can ask from their own tools.',
  lede='The DevOps team knows your infrastructure. The product team knows the requirements and how features are tested. Today everyone waits for them on Slack. With Expert Crews, each team builds a specialist Crew with its knowledge, skills and tools, and shares it. Any engineer can ask it from their own Claude Code, Codex, Cursor or ChatGPT.',
  goal=('Expert answers without the wait','Questions answered by an Expert Crew',('70%','answered without a human, target 60%')),
  pains=[('Experts are the bottleneck','The same infrastructure, database and product questions reach the same few people every day.'),
         ('Knowledge stays in heads and threads','Runbooks, requirements and test plans are scattered, so every answer starts from scratch.'),
         ('Every engineer builds their own agent','People paste context into personal chats and prompts, and no one shares or improves them.')],
  how_h2='Built once by the experts.', how_h2dim='Used by everyone.',
  steps=[('Experts build the agent','The DevOps team sets up a Crew agent with its runbooks, skills, memory and read access to the right systems. The product team does the same for requirements and testing.'),
         ('Offer clear functions','Besides free-text ask, a Crew can offer typed functions such as diagnose_rds(instance) or release_checklist(feature), with inputs and results checked.'),
         ('Share it with the teams','Give people access with scoped tokens. They see what the agent offers, never its private chats, data or settings.'),
         ('Ask from any tool','Engineers call it from Claude Code, Codex, Cursor, ChatGPT or Claude through MCP, or with agentworks crews ask. Each person gets their own conversation with it.')],
  list_kicker='What you get', list_h2='An internal library of expert agents.', list_h2dim='Owned by the teams who know best.',
  list_lede='Examples teams build first. Each is a Crew agent the owning team keeps improving, while everyone else just asks.',
  list_cta='See examples',
  playbooks=['DevOps agent: deploys, pipelines, on-call runbooks','Database agent: RDS and Postgres health, slow queries, safe changes','Product agent: requirements, acceptance criteria, how a feature is tested','Security agent: policies, approved libraries, review checklists','Data agent: where a metric comes from and how to query it','Onboarding agent: how the codebase, services and tools fit together'],
  cta_h2='Pick one expert to share first.', cta_h2dim='See it answer in week one.',
  cta_p='We build your first Expert Crew with the team that owns the knowledge, then connect it to your engineers\' tools.',
  faq=[('How do engineers reach a shared agent?','Through MCP from any client that supports it, such as Claude Code, Codex, Cursor, ChatGPT or Claude, or with the agentworks CLI. They can ask in free text or call its typed functions.'),
       ('Can people see the agent\'s private data?','No. Callers get the agent\'s answers and the files its owners choose to share. Its chats with owners, its database and its settings stay private.'),
       ('Who controls access?','Admins issue scoped tokens per person and per agent. Revoking a token stops its calls immediately, and every call is recorded.'),
       ('Does every caller share one conversation?','No. Each caller gets their own continuing conversation with the agent, and the owners\' main chat stays separate.')]),
 dict(slug='mcp-gateway', path='/vault/', product=True, group='AI platform for teams', nav='Vault', icon='<path d="M4 12h4M16 12h4M12 4v4M12 16v4"/><rect x="8" y="8" width="8" height="8" rx="2"/>',
  navdesc='One governed door to every MCP tool and shared secret your company uses.',
  title='AgentWorks Vault - Govern Every MCP Tool and Shared Secret Your AI Agents Use',
  desc='Vault is one MCP endpoint for every AI client in your company. Admins connect servers once, grant tools and secrets by group, and every call is checked against policy and recorded in an audit log.',
  kicker='Vault · Early access',
  h1='One door to every MCP tool.', h1dim='Every call checked and recorded.',
  lede='People plug MCP servers into Claude, ChatGPT, Cursor and their own agents, each with its own tokens and no oversight. Vault gives your company one governed MCP endpoint: admins connect servers once, people sign in with the company account, and every tool call is checked against the groups and rules you set.',
  cta_label='Get early access',
  goal=('Every MCP tool call governed','Tool calls with a grant and an audit record',('100%','of calls through Vault, target 100%')),
  pains=[('MCP tokens live on every laptop','Each person connects servers with their own keys, so access can\'t be reviewed or revoked in one place.'),
         ('Anyone can call any tool','There is no way to say which team may use which server, let alone which individual tool or what it may be asked to do.'),
         ('Shared secrets get pasted around','API keys and passwords travel through chats and files, with no record of who can use them.')],
  how_h2='Connect once.', how_h2dim='Govern every call.',
  steps=[('Connect servers once','An admin connects an MCP server with OAuth or a custom setup and approves its tool definitions. Connecting a server gives nobody access.'),
         ('Grant by group','Access is deny by default. Give a group individual tools or whole servers, and add rules on a tool\'s inputs, with exact values or patterns.'),
         ('Share secrets without showing them','Let a group use a shared secret without anyone seeing its value.'),
         ('Everything is recorded','Each call is checked again against the current groups and rules, and logged with the person and the AI client that made it.')],
  list_kicker='What it includes', list_h2='Built for your security review.', list_h2dim='From day one.',
  list_lede='Vault is in early access. Book a call to see it and shape what comes next.',
  list_cta='See what it includes',
  playbooks=['One MCP endpoint for Claude, ChatGPT, Cursor and AgentWorks agents','Sign-in with your company account, and each AI client\'s access can be revoked','Deny-by-default grants per group, server or single tool','Rules on tool inputs: exact values or full-string patterns','New or changed tool definitions are held for review','Shared secrets granted to groups without revealing their value','An audit log of every call, with the person and AI client','A chat assistant that sets up access and explains each change'],
  cta_h2='Govern MCP before it sprawls.', cta_h2dim='Join the early access.',
  cta_p='Tell us which MCP servers and AI clients your teams use, and we will set up Vault with you.',
  faq=[('Is Vault available?','It is in early access. Book a call and we will set it up with you.'),
       ('Which MCP clients work with it?','Any client that can connect to a remote MCP server, such as Claude, ChatGPT, Cursor and AgentWorks agents. People sign in with the company account, and a client can be disconnected at any time.'),
       ('Does connecting a server give people access?','No. Access is deny by default. A server\'s tools reach people only through the groups an admin grants them, and new or changed tool definitions wait for review.'),
       ('Can a rule limit what a tool is asked to do?','Yes, for the values a tool exposes as inputs, using exact values or full-string patterns. For things like free-form queries or opaque IDs, also use a narrowly scoped credential upstream.'),
       ('Where does it run?','On your AgentWorks server, in your own cloud or data center.')]),
]

def uc_path(u):
    # Product pages (Code, Crews) live at the top level; the rest are enterprise use cases.
    return u.get('path', f'/enterprise/{u["slug"]}/')

def uc_nav_items():
    soon=' <span class="tag tag-soon">Soon</span>'
    return [(uc_path(u),u['nav']+(soon if u.get('soon') else ''),u['navdesc'],u['icon']) for u in USECASES]

def uc_nav_groups():
    """Enterprise menu columns: (label, nav items) in order of first appearance."""
    items=dict(zip([u['slug'] for u in USECASES], uc_nav_items()))
    out={}
    for u in USECASES:
        out.setdefault(u.get('group','Engineering goals'),[]).append(items[u['slug']])
    return list(out.items())
